### PR TITLE
added the peicewise objective function

### PR DESCRIPTION
**Pull request by samiarja**

### CODE REVIEW

**Comment by aMarcireau** [comment]
@samiarja Strong suggestions before merging:
- The class `OptimizeCMax` has many parameters (such as `resolution`) that are only useful to plot the speed landscape, but they must be specified to initialise the class and use the function `optimise`. This is likely to confuse users. I think that two seperate functions (without a class) would be clearer.
- line 44 in OptimizeCMax.py, why do you filter out events whose timestamp is 0 or 1, and the very last event?
- `implementation.py` has many hard-coded parameters to files on your system, remove it before merging
- Use `raise Exception("some error message")` instead of `print` (for instance line 400 in __init__.py)
- Remove `img_path` line 157 in `__init__.py`
- Remove `mirror` since it is not used anywhere, and rename `mirror_iwe` to `mirror`
- Remove `fun_idx` since it is not used
- Should users pick `DensityInvariantCMax` or `OptimizeCmax`? Remove the other one.
- Document the optimisation parameters.

Nice to have:
- line 20 in `__init__.py`, remove the unused "from PIL import ImageDraw"
- Run black (https://github.com/psf/black) to format the code and pyright (https://github.com/microsoft/pyright) to detect type issues
- Use snake_case for `VarianceLossCalculator` (since it's a function) and `imageOfWarpedEvents` (since it's a variable)
- Use lower case for `EDGEPX` (since it's a variable, not a constant)
- Use lower case in file names
- Add type annotations to `VarianceLossCalculator`, `correction`, `alpha_1`, `alpha_2`, and `mirror_iwe`
- Avoid acronyms such as `iwe` (I think `warped_image` would be clearer)

**Comment by aMarcireau** [comment]
I think that we are likely to see two types of users:
- People interested in the algorithm and its implementation
- People who want to try the algorithm on their data

While the former can read the source code, the latter may struggle a little. I think a short tutorial in the README would be quite useful (something that explains how to use the code with their own data).

**Comment by samiarja** [comment]
Thanks for your feedback Alex. I have carefully addressed each comment and made the necessary changes. Here is my response to your requests:

- I refactor `OptimizeCMax.py` to make it clearer and easier to understand. The filtering of events with timestamps 0, 1, and the last event was a mistake in the index which result in removing some events from the beginning and the end, however, it doesn't impact the dataflow in the code. I have removed this indexing step. The code now processes all events within the user-specified range without excluding specific timestamps.
- In `implementation.py` I have revised the code and removed all hard-coded file paths and replaced them with configurable parameters. Users can now specify the paths to their own data files before running the implementation.
- improve error handling in `init.py` to make debugging easier.
- I have updated the `README` to provide detailed information about the optimization parameters used in `OptimizeCMax` and they can use their own data. This will hopefully help users understand the purpose and usage of each parameter.
- Type annotations, lowercase file names, naming conventions, code formatting and type checking are all done.

I believe that these changes have addressed your suggestions effectively. Please review the updated code and let me know if there is anything else you want me to add.

**Comment by aMarcireau** [comment]
Hey @samiarja 

This looks good! Two last things before merging:
- Can you use snake_case in the name of the file (rename OptimizeCMax.py to optimise_cmax.py)?
- Your branch has conflicts with main, we can address that by rebasing your branch on main. I can help out if you are not familiar with the rebase operation.

**Comment by samiarja** [comment]
This is all done. Sure I will do the rebase with you

**Pull request merged**
